### ISSUE TITLE
How to port to non AVR Arduinos ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [zkemble/nRF905#1]
Hi Zac,

I'd like to use your library on a non AVR Arduino, however this looks like its possibly going to be a bit challenging.
I'm actually trying to port to the STM32 running the Arduino IDE, but the port would equally apply to the Due and the Zero as all of these processors are ARM based.

The main issue I'm having is the interrupt definitions, as none of them exist for the Due etc.

Can you give me some general advice on the best way to approach this port ?

Thanks

Roger Clark

PS. My Arduino for STM32 is in github at https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by ZakKemble** [comment]
Hey, I've made a new branch https://github.com/zkemble/nRF905/commit/00c223fdd243ded1ed7f77dee9dd014f4276f618 which makes use of Arduino's attachInterrupt() and detactInterrupt() functions instead of plain ISRs. I've not tested it on hardware, but it compiles ok for the Due and Uno. That should help you with what you're doing.

**Comment by rogerclarkmelbourne** [comment]
Thanks Zac, I will take a look.

Yesterday, I managed to get it to compile, by commenting out a load of the defines that only apply to the AVR and used attachInterrupt and detachInterrupt; however I've not had time to extensively test my changes, because so far I only physically wired up one NRF905. I do however have one of those TV receiver dongles and by runnng SDR-Sharp i can see that the transmitter is sendng some data, but i'm not enitirely sure i got the ISR stuff right, so it will be good to try you code.

I will clone your repo, so i can create, pull request if I manage to get a cross platform version working.

Thanks again

Roger

**Comment by rogerclarkmelbourne** [comment]
I have managed to get my port of the lib working.

I needed to slow the SPI down to DIV4, but its now OK.

I will try modifying your branch and see if I can get it to work just by setting DIV4

I will let you know how I get on

**Comment by stevstrong** [comment]
Hi Roger, could you share the ported code? I would be interested to test it.

**Comment by rogerclarkmelbourne** [comment]
I got it working for what I needed at the time, but I just reworked the bare minimum functionality that I needed for the project I was doing.

The reason that I didn't fully port the library, is because the code is not really a library.
If you look in nrf905.c and .h it's not a class, it's just a load of functions.

@stevstrong , if you need to get something working quickly, I will find my code, and PM it to you, but it's not that good ;-)

**Comment by ZakKemble** [comment]
> The reason that I didn't fully port the library, is because the code is not really a library.
> If you look in nrf905.c and .h it's not a class, it's just a load of functions.

It's written in C. The only way a C library can be written is with a bunch of functions...  😕

**Comment by rogerclarkmelbourne** [comment]
Sorry. It wasnt meant to be a criticism 

Its just that, most Arduino libs now seem to be written in C++ as a class

**Comment by ZakKemble** [comment]
Closing super old issue, new Arduino C++ library now available at https://github.com/zkemble/nRF905-arduino
