### ISSUE TITLE
Frequency change

### ISSUE THREAD

**Issue by marc-gist** [zkemble/nRF905#2]
nRF905_setFrequency(NRF905_BAND_915, 915000000UL);

doesn't work in your ping_server/client examples on Arduino's... I put this before '_receive()' in setup.

**Comment by ZakKemble** [comment]
Does nRF905_setChannel(NRF905_BAND_915, 351); work? Channel 351 is 915MHz on the 868/915MHz band.

**Comment by marc-gist** [comment]
I've tried a number of different channels on the 868/915MHz bands... none work... I can set the channel in the 433 band and that appears to work.

If I change in the debug program, it will print the correct frequency, but when I use in your ping it doesnt.

I'm using two 3.3v 8Mhz arduino pro minis.

**Comment by ZakKemble** [comment]
Your radio modules are probably tuned for 433MHz operation, the component placement and values are a little different for 868/915MHz (the datasheet has schematics for each band). Using the wrong band will result in low transmit output power and poor receive sensitivity. Have you tried putting the modules right next to each other?

**Comment by marc-gist** [comment]
They are about 6" away from each other... but I did finally come across that you need to "tune" them and how.  Was hoping it was as simple as a firmware setting, but guess not.

Thanks for the great library and fast responses!!!
