### ISSUE TITLE
default channel

### ISSUE THREAD

**Issue by mcauser** [zkemble/nRF905#6]
I noticed in `defaultConfig()` you set the default channel to 108 (433.2MHz), however, when I listen to /examples/ping_client/ping_client.ino with a logic analyzer, I see the channel being set as 216 over SPI.

I saw your note in /arduino/nRF905/nRF905.h about the high band being set as 0x02 as its bit shifted right by 1. I am not sure about this one... Right shifting the band so the math in your NRF905_CALC_CHANNEL macro is simpler?
```
// NOTE:
// When using NRF905_BAND_868 and NRF905_BAND_915 for calculating channel (NRF905_CALC_CHANNEL(f, b)) they should be value 0x01,
// but when using them for setting registers their value should be 0x02.
// They're defined as 0x02 here so when used for calculating channel they're right shifted by 1
```
I get it but...

eg.
#define NRF905_CALC_CHANNEL(f, b)	((((f) / (1 + (b>>1))) - 422400000UL) / 100000UL)
NRF905_CALC_CHANNEL(444000000, 0) == 216     :)
NRF905_CALC_CHANNEL(444000000, 1) == 216      o.O
NRF905_CALC_CHANNEL(888000000, 0) == 4656    >.<
NRF905_CALC_CHANNEL(888000000, 1) == 4656    >.<
NRF905_CALC_CHANNEL(888000000, 2) == 216     :)

The nRF905 datasheet suggests using formula:
`Frequency in MHz = (422.4 + (CH_NO/10)) * (1+HFREQ_PLL)`
(CH_NO/10 as the low band has 0.1MHz steps, high band 0.2MHz steps)
Which can be rewritten as:
`Frequency in Hz = 422,400,000 + (channel * 100,000) * (1 + band)`

Not sure why you are storing the high band as 0x02 then right shifting by 1, when you could just store the band bit (HFREQ_PLL) as 0x00 or 0x01.

If you change the macro to skip shifting the b(and)
`#define NRF905_CALC_CHANNEL(f, b)	((((f) / (1 + b)) - 422400000UL) / 100000UL)`
and change the `nRF905_band_t` enum to use 0x01 for NRF905_BAND_868 and NRF905_BAND_915, doesn't that make more sense?

You should also & 0xff the channel in `spi_transfer_nr(channel);` in `defaultConfig()` to eliminate the MSB set in reg1.

In the nRF905 datasheet, Channel (CH_NO) is 9 bits, and the MSB is stored in the 2nd byte of the config register, along with Band (HFREQ_PLL).
Byte 0 = **CH_NO[7:0]**
Byte 1 = bit[7:6] not used, AUTO_RETRAN, RX_RED_PWR, PA_PWR[1:0], HFREQ_PLL, **CH_NO[8]**

If I set the channel to 364 (1 0110 1100), I would expect to see the least 8 bits (0110 1100) sent to Byte 0 and the most significant bit (1) sent to the Byte 1 as the least significant bit. When setting reg1 you are putting the MSB in there as I would expect ((channel>>8) & 0x01).

**Unless I am totally wrong and CH_NO[8] in the datasheet refers to the LSB, not MSB!**

Low band (HFREQ_PLL=0)
Channel 108 = 433.2MHz (422.4 + (108 * 0.1MHz))
Channel 216 = 444.0MHz (422.4 + (216 * 0.1MHz))

High band (HFREQ_PLL=1)
Channel 108 = 866.4MHz (844.8 + (108 * 0.2MHz))
Channel 216 = 888.0MHz (844.8 + (216 * 0.2MHz))

/arduino/nRF905/nRF905_config.h:
```
#define NRF905_FREQ			433200000UL
#define NRF905_BAND			NRF905_BAND_433
```

/arduino/nRF905/nRF905_defs.h:
```
#define NRF905_CALC_CHANNEL(f, b)	((((f) / (1 + (b>>1))) - 422400000UL) / 100000UL)
```

/arduino/nRF905/nRF905.cpp:
```
uint16_t channel = NRF905_CALC_CHANNEL(NRF905_FREQ, NRF905_BAND);
```

/arduino/nRF905/nRF905.cpp:
```
spi_transfer_nr(NRF905_CMD_W_CONFIG);
spi_transfer_nr(channel);
spi_transfer_nr(reg1);
spi_transfer_nr((NRF905_ADDR_SIZE<<4) | NRF905_ADDR_SIZE);
spi_transfer_nr(NRF905_PAYLOAD_SIZE); // RX payload size
spi_transfer_nr(NRF905_PAYLOAD_SIZE); // TX payload size
for(uint8_t i=4;i--;)
	spi_transfer_nr(0xE7); // Default receive address
spi_transfer_nr(reg2);
```

Is being captured as:
```
MOSI: 0  = NRF905_CMD_W_CONFIG
MOSI: 216  = channel
MOSI: 12  = reg1
MOSI: 68  = NRF905_ADDR_SIZE
MOSI: 32  = RX NRF905_PAYLOAD_SIZE
MOSI: 32  = TX NRF905_PAYLOAD_SIZE
MOSI: 231  = Default receive address (1/4)
MOSI: 231  = Default receive address (2/4)
MOSI: 231  = Default receive address (3/4)
MOSI: 231  = Default receive address (4/4)
MOSI: 32  = reg2
```

2x Saleae Logic captures attached:
[ping_client.zip](https://github.com/zkemble/nRF905/files/843190/ping_client.zip)

You can open them with the free Saleae Logic app, if you don't already have it: https://www.saleae.com/downloads

**Comment by mcauser** [comment]
I'll try listening with a RTL-SDR to see if I can see which channel the devices are communicating on.

**Comment by ZakKemble** [comment]
> NRF905_CALC_CHANNEL(444000000, 0) == 216 :)
> NRF905_CALC_CHANNEL(444000000, 1) == 216 o.O
> NRF905_CALC_CHANNEL(888000000, 0) == 4656 >.<
> NRF905_CALC_CHANNEL(888000000, 1) == 4656 >.<
> NRF905_CALC_CHANNEL(888000000, 2) == 216 :)

These outputs are correct and expected. Right shifting 0 or 1 will give you 0, which is why the first 2 are the same.
The last 3 outputs are expected, since you're supposed to use NRF905_BAND_868/NRF905_BAND_915 for the second parameter, which are defined as the value 2 (NRF905_BAND_433 is 0).

Storing the band bit as 0 and 1 will then require a left shift in the nRF905_setChannel() function and maybe a few other places, so it's going to need a shift somewhere, I just decided to stick it in the NRF905_CALC_CHANNEL macro and use values 0 and 2.

There's no need for `& 0xff` in `spi_transfer_nr(channel);`, since the parameter is of type `uint8_t`, so it already truncates the data to the lower 8 bits for free.

Now, why you're getting 216 for the channel from 433.2MHz is very odd, it seems to been shifting itself to the left by 1... I'll have to a closer look later.

**Comment by mcauser** [comment]
Proposed changes here: https://github.com/mcauser/nRF905/tree/default_channel

[ping_client_v2.zip](https://github.com/zkemble/nRF905/files/844705/ping_client_v2.zip)

Now captured as:
```
MOSI: 0  = NRF905_CMD_W_CONFIG
MOSI: 108  = channel
MOSI: 12  = reg1
MOSI: 68  = NRF905_ADDR_SIZE
MOSI: 32  = RX NRF905_PAYLOAD_SIZE
MOSI: 32  = TX NRF905_PAYLOAD_SIZE
MOSI: 231  = Default receive address (1/4)
MOSI: 231  = Default receive address (2/4)
MOSI: 231  = Default receive address (3/4)
MOSI: 231  = Default receive address (4/4)
MOSI: 34  = reg2
```

Confirmed with RTL-SDR, MOSI 108 is bang on 433.2MHz:

<img width="2029" alt="433 2mhz" src="https://cloud.githubusercontent.com/assets/1038959/23952286/20ec73c0-09e5-11e7-9b1f-900137425f97.png">

**Comment by mcauser** [comment]
Figured out what the channel 216 was.

I had modified nRF905_config.h to use channel 216:
```
#define NRF905_FREQ			444000000UL
```

but then changed to back to `433200000UL` channel 108, but didn't restart my Arduino IDE.
The old config was being cached.
Restarted the IDE, and it's back to 108!

**Comment by mcauser** [comment]
_Have you tried turning it off and on again..._
