### ISSUE TITLE
How to wire with "Pro Micro"

### ISSUE THREAD

**Issue by Ekiszzero** [zkemble/nRF905#7]
Hi Zak,

I have just sent you an email asking the same question, I do not know how often you check your email, so I am writing to you by this mean as well, just in case.

I would like to use the library with a "Pro Micro" (
https://www.sparkfun.com/products/12640 ) board.  which files should  I modify in order to get the library works?. Is it only necessary to modify the file "nRF905_config.h" (section Pin Stuff)?

Regards,

**Comment by ZakKemble** [comment]
Hey @Ekiszzero, yup, nRF905_config.h should be the only file that needs to be modified. Though, I don't think anything needs to be changed since the pins defined in the config h are already available on the Pro Micro.
