### ISSUE TITLE
RX buffer is not clearing last digit.

### ISSUE THREAD

**Issue by dharmik768** [zkemble/nRF905#8]
![image](https://user-images.githubusercontent.com/43682902/97434920-bc72a580-1945-11eb-98e8-5f7e12ec1fbf.png)
I was trying to send a different button data with this library so as you see when I press button 4 then it sends 4 and the receiver receives 4 it's perfect.
now when I press button 12 it sends 12 and the receiver receives 12. Now the problem starts for no reason it stores the last digit of the received value.

after reading the data I had tried to put the module in standby and power-down mode and back to power on and RX mode but the issue is still there.

so when I press button 4 now then the transmitter is sending 4 as data but the receiver is saying that it's button 42.
See the attached image.
Can you please guide me to fix this problem.

**Comment by ZakKemble** [comment]
This is because the transmit buffer of the nRF905 is not automatically cleared when a new payload is loaded. If the first payload contains 3 bytes "A", "B" and "C", and then the second payload only contains 2 bytes "6", "7" then the next transmitted payload will be "6", "7", "C".

There are a few ways of working around this:
1. The first byte of the payload could contain the payload length so the receiving end knows how many bytes to look at and how many to ignore.
2. Use my newer nRF905 library [here](https://github.com/zkemble/nRF905-arduino) and blank out the transmit buffer before writing your data like this:

```
uint8_t blankBuff[NRF905_MAX_PAYLOAD] = {0};
transceiver.write(TXADDR, blankBuff, sizeof(blankBuff));

// your code here
transceiver.write(TXADDR, myData, 2);
```

Option 1 would be the more efficient and proper way of doing it, as well as updating to the new library :)

**Comment by dharmik768** [comment]
I am using this logic to make my transmitting packet. Also clearing the s_data char array with memset function before making a new packet.

```
void convert_int_char()
{
  memset(s_data, 0, sizeof(s_data)); 
  data_btn = String(btn_data); 
  data_btn.toCharArray(s_data, sizeof(data_btn)); 
  //String(btn_data).toCharArray(s_data, String(btn_data).length());
  Serial.println(temp);
  Serial.println(btn_data);
  Serial.println(s_data);
}
```


Then I am sending s_data with the following function. 
```
void send_data()
{
  nRF905_powerUp();
  delay(100);
  while (!nRF905_TX(TXADDR, s_data, data_btn.length(), NRF905_NEXTMODE_STANDBY));
}
```

**Comment by ZakKemble** [comment]
In nRF905_TX() you are using data_btn.length() so it will only send up to the end of the string, not the whole array.
Why not send the value as a single byte instead of converting to string?
```
s_data[0] = btn_data;
while (!nRF905_TX(TXADDR, s_data, 1, NRF905_NEXTMODE_STANDBY));
```

**Comment by dharmik768** [comment]
btn_data is an integer type variable. 
I tried  s_data[0] = btn_data; 
but this was the result on serial monitor it considers 64 as @  I think it is converting into ascii formate.
```
Starting.
NRF Client started
SLEEPING
Key down: u

64
@
Key down: U

192
⸮
```

**Comment by ZakKemble** [comment]
Split the integer into 2 bytes:
```
s_data[0] = btn_data>>8;
s_data[1] = btn_data;
while (!nRF905_TX(TXADDR, s_data, 2, NRF905_NEXTMODE_STANDBY));
```

Yes, your serial terminal will display the received bytes as ASCII. `Serial.println(value, DEC);` will make the Arduino convert the value to a string before sending it so it becomes human-readable on the terminal.

**Comment by dharmik768** [comment]
Finally I got the solution for my issue.
I had just changed this line 
```
while (!nRF905_TX(TXADDR, s_data, data_btn.length(), NRF905_NEXTMODE_STANDBY));
```
with this one
```
while (!nRF905_TX(TXADDR, s_data,sizeof(s_data), NRF905_NEXTMODE_STANDBY));
```
and now it works as expected.
Thanks for your help zkemble.
and thanks for the library also.
![image](https://user-images.githubusercontent.com/43682902/97563730-7a129c80-1a09-11eb-99c6-6d852e1267ed.png)
